#!/usr/bin/env python3
#
# test (python3 executable)
# authors: Michael Curley & Drake Moore
#

from os import listdir
from sys import path
from unittest import main as runUnitTests


if __name__ == '__main__':
    path.append('../')
    pythonFiles = filter(lambda f: f.endswith('.py'), listdir('.'))
    pythonFilesNoExtension = map(lambda f: f[:-3], pythonFiles)
    for testFile in pythonFilesNoExtension:
        testClass = testFile[0].upper() + testFile[1:]
        try:
            exec('from {0} import {1}'.format(testFile, testClass))
        except Exception as e:
            print('Test class {0} could not be imported from {1}:\n\t{2}'.format(
                testClass, testFile, e))

    # run the imported tests
    runUnitTests()


# ----- end of file ------------------------------------------------------------





