#!/usr/bin/env python3
#
# snarlClient3 (python3 executable)
# authors: Michael Curley & Drake Moore
# notes:
#   - this is a copy of the original snarlClient and may be used the exact same
#     way, only difference being this client allows the user to register as an
#     adversary and play via command line, however is no argument is specified
#     the same behavior follows so we are using this as our updated client to
#     not have as many duplicated files
#

from argparse import ArgumentParser, Namespace
from clientController import ClientController
from consoleController import ConsoleController


def main():
    args = parseArguments()
    controller = ClientController(ConsoleController(), args.address, args.port, args.type)
    controller.run()

def parseArguments() -> Namespace:
    """ returns a Namespace containing the command line arguments, additional
    verification is required for arguments that interact with each other """
    ap = ArgumentParser(description = 'play a remote game of snarl over a network')
    ap.add_argument('--address', metavar = 'IP', type = str, default = '127.0.0.1',
            help = 'where IP is an IP address the client should connect to')
    ap.add_argument('--port', metavar = 'NUM', type = int, default = 45678,
            help = 'where NUM is the port number the client should connect to')
    ap.add_argument('--type', metavar = 'TYPE', type = str, default = None,
            help = 'the type of client you wish to be, either player, ghost or zombie')
    return ap.parse_args()

if __name__ == '__main__':
    main()


# ----- end of file ------------------------------------------------------------





